const TASK_TYPES = {
  FETCH_GET_ALL_START: 'FETCH_GET_ALL_START',
  FETCH_GET_ALL_SUCCESS: 'FETCH_GET_ALL_SUCCESS',
  FETCH_GET_ALL_ERROR: 'FETCH_GET_ALL_ERROR',

  FETCH_GET_MY_TASKS_START: 'FETCH_GET_MY_TASKS_START',
  FETCH_GET_MY_TASKS_SUCCESS: 'FETCH_GET_MY_TASKS_SUCCESS',
  FETCH_GET_MY_TASKS_ERROR: 'FETCH_GET_MY_TASKS_ERROR',

  FETCH_GET_PENDING_TASKS_START: 'FETCH_GET_PENDING_TASKS_START',
  FETCH_GET_PENDING_TASKS_SUCCESS: 'FETCH_GET_PENDING_TASKS_SUCCESS',
  FETCH_GET_PENDING_TASKS_ERROR: 'FETCH_GET_PENDING_TASKS_ERROR',

  FETCH_GET_TASK_START: 'FETCH_GET_TASK_START',
  FETCH_GET_TASK_SUCCESS: 'FETCH_GET_TASK_SUCCESS',
  FETCH_GET_TASK_ERROR: 'FETCH_GET_TASK_ERROR',
  CLEAR_GET_TASK_ERROR: 'CLEAR_GET_TASK_ERROR',

  FETCH_CREATE_TASK_START: 'FETCH_CREATE_TASK_START',
  FETCH_CREATE_TASK_SUCCESS: 'FETCH_CREATE_TASK_SUCCESS',
  FETCH_CREATE_TASK_ERROR: 'FETCH_CREATE_TASK_ERROR',

  FETCH_UPDATE_TASK_START: 'FETCH_UPDATE_TASK_START',
  FETCH_UPDATE_TASK_SUCCESS: 'FETCH_UPDATE_TASK_SUCCESS',
  FETCH_UPDATE_TASK_ERROR: 'FETCH_UPDATE_TASK_ERROR',

  FETCH_DELETE_TASK_START: 'FETCH_DELETE_TASK_START',
  FETCH_DELETE_TASK_SUCCESS: 'FETCH_DELETE_TASK_SUCCESS',
  FETCH_DELETE_TASK_ERROR: 'FETCH_DELETE_TASK_ERROR',

  FETCH_COMPLETE_TASK_START: 'FETCH_COMPLETE_TASK_START',
  FETCH_COMPLETE_TASK_SUCCESS: 'FETCH_COMPLETE_TASK_SUCCESS',
  FETCH_COMPLETE_TASK_ERROR: 'FETCH_COMPLETE_TASK_ERROR',

  FETCH_REJECT_TASK_START: 'FETCH_REJECT_TASK_START',
  FETCH_REJECT_TASK_SUCCESS: 'FETCH_REJECT_TASK_SUCCESS',
  FETCH_REJECT_TASK_ERROR: 'FETCH_REJECT_TASK_ERROR',

  REDIRECT_CREATE_TASK: 'REDIRECT_CREATE_TASK',
};
export default TASK_TYPES;
